/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as ModelRouteImport } from './routes/model'
import { Route as LiveRouteImport } from './routes/live'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ClusterRouteImport } from './routes/cluster'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterRoute = ClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cluster': typeof ClusterRoute
  '/events': typeof EventsRoute
  '/live': typeof LiveRoute
  '/model': typeof ModelRoute
  '/monitoring': typeof MonitoringRoute
  '/storage': typeof StorageRoute
  '/telegram': typeof TelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cluster': typeof ClusterRoute
  '/events': typeof EventsRoute
  '/live': typeof LiveRoute
  '/model': typeof ModelRoute
  '/monitoring': typeof MonitoringRoute
  '/storage': typeof StorageRoute
  '/telegram': typeof TelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cluster': typeof ClusterRoute
  '/events': typeof EventsRoute
  '/live': typeof LiveRoute
  '/model': typeof ModelRoute
  '/monitoring': typeof MonitoringRoute
  '/storage': typeof StorageRoute
  '/telegram': typeof TelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/cluster'
    | '/events'
    | '/live'
    | '/model'
    | '/monitoring'
    | '/storage'
    | '/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/cluster'
    | '/events'
    | '/live'
    | '/model'
    | '/monitoring'
    | '/storage'
    | '/telegram'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/cluster'
    | '/events'
    | '/live'
    | '/model'
    | '/monitoring'
    | '/storage'
    | '/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ClusterRoute: typeof ClusterRoute
  EventsRoute: typeof EventsRoute
  LiveRoute: typeof LiveRoute
  ModelRoute: typeof ModelRoute
  MonitoringRoute: typeof MonitoringRoute
  StorageRoute: typeof StorageRoute
  TelegramRoute: typeof TelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster': {
      id: '/cluster'
      path: '/cluster'
      fullPath: '/cluster'
      preLoaderRoute: typeof ClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ClusterRoute: ClusterRoute,
  EventsRoute: EventsRoute,
  LiveRoute: LiveRoute,
  ModelRoute: ModelRoute,
  MonitoringRoute: MonitoringRoute,
  StorageRoute: StorageRoute,
  TelegramRoute: TelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
