apiVersion: v1
kind: Service
metadata:
  name: edge-backend-canary-lb
  namespace: edge-monitoring
  labels:
    app: edge-backend-canary-lb
spec:
  type: ClusterIP
  sessionAffinity: None

  selector:
    deployment-role: canary

  ports:
    - name: http
      port: 8000
      targetPort: backend-http
