apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-filer-data
  namespace: seaweedfs
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: filer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-rpi3-01
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
