prometheus-node-exporter:
  enabled: false

prometheus:
  service:
    type: NodePort
    port: 9090
    targetPort: 9090
    nodePort: 30090

  prometheusSpec:
    retention: 7d

    resources:
      requests:
        memory: 300Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 1000m

    additionalScrapeConfigs:
      - job_name: "raspberry-pi-nodes"
        scrape_interval: 15s
        scrape_timeout: 10s
        static_configs:
          - targets:
              - "192.168.178.200:9100"
              - "192.168.50.101:9100"
              - "192.168.50.102:9100"
              - "192.168.50.103:9100"
              - "192.168.50.104:9100"
              - "192.168.50.105:9100"
              - "192.168.50.106:9100"
              - "192.168.50.107:9100"
              - "192.168.50.108:9100"

grafana:
  enabled: true
  replicas: 1

alertmanager:
  enabled: true

kube-state-metrics:
  enabled: true
