prometheus-node-exporter:
  enabled: false

grafana:
  enabled: true

alertmanager:
  enabled: true

prometheus:
  service:
    type: ClusterIP
    port: 9090

  prometheusSpec:
    retention: 7d

    additionalScrapeConfigs:
      - job_name: "raspberry-pi-nodes"
        scrape_interval: 15s
        static_configs:
          - targets:
              - "192.168.50.1:9100"
              - "192.168.50.101:9100"
              - "192.168.50.102:9100"
              - "192.168.50.103:9100"
              - "192.168.50.104:9100"
              - "192.168.50.105:9100"
              - "192.168.50.106:9100"
              - "192.168.50.107:9100"
              - "192.168.50.108:9100"
